# Generated by Django 2.2.11 on 2020-03-26 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='all_lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson', models.CharField(max_length=32)),
                ('teacher', models.CharField(max_length=32)),
                ('location', models.CharField(max_length=32)),
                ('classes', models.CharField(max_length=32)),
                ('credit', models.CharField(max_length=8)),
                ('user', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='user_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=9)),
                ('pws', models.CharField(max_length=32)),
            ],
        ),
    ]
