# Generated by Django 2.2.11 on 2020-03-26 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_info',
            old_name='pws',
            new_name='pwd',
        ),
    ]
