# Generated by Django 2.2.11 on 2020-03-28 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_auto_20200326_0616'),
    ]

    operations = [
        migrations.CreateModel(
            name='lesson_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(max_length=256)),
            ],
        ),
    ]
