# Generated by Django 2.2.11 on 2020-03-28 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_lesson_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson_info',
            name='user',
            field=models.CharField(default='', max_length=32),
        ),
    ]
