# Generated by Django 2.2.11 on 2020-03-28 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0005_auto_20200328_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson_info',
            name='times',
        ),
        migrations.AlterField(
            model_name='user_info',
            name='times',
            field=models.CharField(default='0', max_length=3),
        ),
    ]
